# NeoForge and Minecraft versions
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.0
neo_version_range=[21.1,22)
loader_version_range=[4,)

# Mod properties
mod_id=raeynantiacheat
mod_name=RaeYNAntiCheat
mod_license=MIT
mod_version=1.0.0
mod_authors=RaeYNCreations
mod_description=Server-side anti-cheat for NeoForge servers

# Gradle properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false
